spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          auth: true
    host: smtp.gmail.com
    username: sethu10121994@gmail.com
    password: pnazmvndkeyzmfgw
    port: 587